# Agent Configuration Template
name: "CustomAgent"
description: "Description of your custom agent"

# Agent settings
settings:
  model: "gpt-4"  # or any other supported model
  temperature: 0.7
  max_tokens: 2000

# Tools configuration
tools:
  - name: "custom_tool"
    enabled: true
    config:
      param1: "default_value"
      param2: 42

# Memory configuration
memory:
  type: "conversation"  # or "vector" for vector-based memory
  max_history: 10

# System prompt template
system_prompt: |
  You are a helpful assistant specialized in [describe your agent's specialty].
  Your capabilities include:
  - [capability 1]
  - [capability 2]
  - [capability 3]

# Example conversation starters
examples:
  - "How can you help me with [task]?"
  - "What are your main capabilities?"
  - "Can you explain how you work?" 